---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
