---
# SPDX-FileCopyrightText: (c) 2022 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later

name: "Release"
permissions: {}
on:
  create:
    tags:
      - "v*"
  workflow_dispatch:
    tags:
      - "v*"
if: "startsWith(github.ref, 'refs/tags/v')"
jobs:
  base-job:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Build"
        shell: bash
        run: |
          ### Building...
          '${{ github.workspace }}/gradlew' clean buildOtaOSS
      - name: "Upload release"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: "output/*.zip*"
          body: "See the full [**changelog**](./CHANGELOG.rst)."
          replacesArtifacts: false
