---
# SPDX-FileCopyrightText: (c) 2021 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later

name: "Code linting"
permissions: {}
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  shellchecker:
    name: "ShellChecker"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "ShellChecker"
        uses: a5k-actions/shellchecker@v0

  json-yaml-validate:
    name: "JSON and YAML"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "JSON and YAML - Validator"
        uses: GrantBirki/json-yaml-validate@v3
